// // import localFont from "next/font/local";
// // import "./globals.css";
// // import { ShoppingCart, Search, Menu, LogOut } from "lucide-react";
// // import Link from "next/link";
// // import { cookies } from "next/headers";
// // import LogoutButton from "./LogoutButton";

// // const geistSans = localFont({
// //   src: "./fonts/GeistVF.woff",
// //   variable: "--font-geist-sans",
// //   weight: "100 900",
// // });
// // const geistMono = localFont({
// //   src: "./fonts/GeistMonoVF.woff",
// //   variable: "--font-geist-mono",
// //   weight: "100 900",
// // });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children }) {
// //   const cookieStore = cookies();
// //   const token = cookieStore.get("token");

// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         <nav className="bg-gradient-to-r from-blue-500 to-purple-600">
// //           <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
// //             <div className="flex items-center justify-between h-16">
// //               <div className="flex items-center">
// //                 <span className="text-white text-xl font-bold">
// //                   Eco-Action Tracking
// //                 </span>
// //               </div>
// //               <div className="hidden md:block">
// //                 <div className="ml-10 flex items-baseline space-x-4">
// //                   <Link
// //                     className="text-white hover:bg-white hover:bg-opacity-20 px-3 py-2 rounded-md"
// //                     href="/"
// //                   >
// //                     Home
// //                   </Link>

// //                   {!token && (
// //                     <Link
// //                       className="text-white hover:bg-white hover:bg-opacity-20 px-3 py-2 rounded-md"
// //                       href="/login"
// //                     >
// //                       Login
// //                     </Link>
// //                   )}
// //                   {token && <LogoutButton />}
// //                 </div>
// //               </div>
// //               <div className="flex items-center">
// //                 <button className="text-white p-2 rounded-full hover:bg-white hover:bg-opacity-20 ml-4 md:hidden">
// //                   <Menu className="h-6 w-6" />
// //                 </button>
// //               </div>
// //             </div>
// //           </div>
// //         </nav>
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }
// /////////////////////

// import localFont from "next/font/local";
// import "./globals.css";
// import { ShoppingCart, Search, Menu, LogOut } from "lucide-react";
// import Link from "next/link";
// import { cookies } from "next/headers";
// import LogoutButton from "./LogoutButton";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Eco-Action Tracking",
//   description:
//     "A platform for tracking environmental actions and promoting sustainability.",
// };

// export default function RootLayout({ children }) {
//   const cookieStore = cookies();
//   const token = cookieStore.get("token");

//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <nav className="bg-gradient-to-r from-green-500 to-blue-500">
//           <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
//             <div className="flex items-center justify-between h-16">
//               <div className="flex items-center">
//                 <span className="text-white text-xl font-bold">
//                   Eco-Action Tracking
//                 </span>
//               </div>
//               <div className="hidden md:block">
//                 <div className="ml-10 flex items-baseline space-x-4">
//                   <Link
//                     className="text-white hover:bg-white hover:bg-opacity-20 px-3 py-2 rounded-md"
//                     href="/"
//                   >
//                     Home
//                   </Link>

//                   {!token && (
//                     <Link
//                       className="text-white hover:bg-white hover:bg-opacity-20 px-3 py-2 rounded-md"
//                       href="/login"
//                     >
//                       Login
//                     </Link>
//                   )}
//                 </div>
//               </div>
//               <div className="flex items-center justify-end space-x-4 w-full">
//                 {token && <LogoutButton />}
//                 <button className="text-white p-2 rounded-full hover:bg-white hover:bg-opacity-20 ml-4 md:hidden">
//                   <Menu className="h-6 w-6" />
//                 </button>
//               </div>
//             </div>
//           </div>
//         </nav>
//         {children}
//       </body>
//     </html>
//   );
// }
///////////////////////////////////////

import localFont from "next/font/local";
import "./globals.css";
import { cookies } from "next/headers";
import Navbar from "../app/Navbar/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Eco-Action Tracking",
  description:
    "A platform for tracking environmental actions and promoting sustainability.",
};

export default function RootLayout({ children }) {
  const cookieStore = cookies();
  const token = cookieStore.get("token");

  // Check if the current page is the login page
  const isLoginPage = children.type.name === "Login";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {!isLoginPage && <Navbar token={token} />}
        {children}
      </body>
    </html>
  );
}
